import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "EComm Finance Automation Converter",
  description: "Generated by Benby",
  icons: {
    icon: [
      {
        url: "../../Style/Images/favicon.png", // Updated URL to point to the favicon
        href: "../../Style/Images/favicon.png", // Updated href as well if necessary
      }
    ]
  }
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
