import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// Define baseUrl environment variable
const baseUrl = process.env.baseUrl || '';

export const metadata: Metadata = {
  title: "EComm Finance Automation Converter",
  description: "Generated by Benby",
  icons: {
    icon: [
      {
        // Use the baseUrl to construct the absolute URL for the favicon image
        url: `${baseUrl}/favicon.png`,
        href: `${baseUrl}/favicon.png`, // You can update href as well if necessary
      }
    ]
  }
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
